//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TECHNETWORK.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Developer
    {
        public int Id { get; set; }
        public string Developer_name { get; set; }
        public string Designation { get; set; }
        public string Developer_code { get; set; }
        public string Email_id { get; set; }
        public string Phone_number { get; set; }
        public string Details { get; set; }
        public string Address { get; set; }
    }
}
