//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TECHNETWORK.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Product_id { get; set; }
        public string Product_name { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Storage_require { get; set; }
        public string Details { get; set; }
    }
}
